# Configuration for the typos spell checker utility (<https://github.com/crate-ci/typos>).

[files]
extend-exclude = [
    # "uefi/src/table/boot.rs"
]

[default.extend-words]
Rela = "Rela"

[default.extend-identifiers]
# FOOBAR = "FOOBAR"

