[package]
name = "integration-test-util"
description = "Integration Test Utils"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
good_memory_allocator = { workspace = true, features = ["spin"] }
log = { workspace = true }
qemu-exit = { workspace = true }
